### ISSUE TITLE
auto_gen_residual_images.py missed the sequence10

### ISSUE THREAD

**Issue by fengluodb** [haomo-ai/MotionSeg3D#5]
https://github.com/haomo-ai/MotionSeg3D/blob/dc4c95fcdba2f0819d2bbc4a419f231c55e9c6f3/utils/auto_gen_residual_images.py#L152-L154

the script generate for sequence0~9, but miss the sequence 10

https://github.com/haomo-ai/MotionSeg3D/blob/dc4c95fcdba2f0819d2bbc4a419f231c55e9c6f3/config/labels/semantic-kitti-mos.raw.yaml#L180-L190

**Comment by MaxChanger** [comment]
Hi @fengluodb, thank you for such meticulous debuging.

The `gen_residual_images.py` is borrowed from LMNet, and in order to run more automatically, I added this `for` loop scripts in`auto_xxx`. 
However, it is still processed serially and not multi-threaded, it may take many hours to produce all the data, so it may have been manually divided into multiple threads (for i in range(0, 2), range(2,5) ...) and forgotten to modify it back.

It should be noted that the residual images of test-set also needs to be generated, that is, it should be range(0,22), and range(30, 42) for KITTI-road set.

**Comment by fengluodb** [comment]
Thank you for your reply. I forget that test dataset also can generate residual image for infer.
